### ISSUE TITLE
Razor Pages demo with tag helpers

### ISSUE THREAD

**Issue by gerryge** [iyilm4z/admin-lte-dotnet#1]
Do you have plan to give a Razor Pages demo with tag helpers. As you known, Microsoft recommend using Razor Pages.

**Comment by iyilm4z** [comment]
Hi @GerryGe, thanks for your concern on the repo. Yes i know and i actually haven't plan it. However i would like to make AdminLte.TagHelpers module more advanced and flexible. There are some missing parts of it. We can participate in your requirement and missing parts. Finally i would publish AdminLte.TagHelpers on nuget.

**Comment by gerryge** [comment]
Thanks.

**Comment by iyilm4z** [comment]
@GerryGe FYI, demo project for TagHelpers implementation rewritten with RazorPages. [Here](https://github.com/iyilm4z/admin-lte-dotnet/tree/master/src/AdminLte.TagHelpers.Demo) it is.

**Comment by gerryge** [comment]
Great!👍
