### ISSUE TITLE
Use component

### ISSUE THREAD

**Issue by gerryge** [iyilm4z/admin-lte-dotnet#2]
Why don't you use component?

**Comment by iyilm4z** [comment]
@GerryGe Definitely makes sense. If you have time, would you like to do it for us?

**Comment by gerryge** [comment]
Ok, I have done this in my project, I can help this if I have time I'll make a pull request.

**Comment by iyilm4z** [comment]
@GerryGe thanks man.

**Comment by iyilm4z** [comment]
@GerryGe I'm working on this.

**Comment by iyilm4z** [comment]
@GerryGe Done.

**Comment by gerryge** [comment]
Thanks for your hard work. 👍
