### ISSUE TITLE
Add documentation for configuring Project

### ISSUE THREAD

**Issue by vivekout** [iyilm4z/admin-lte-dotnet#3]
Need to add documentation for configuring the project so user can easily setup this project in their environment and run locally.

**Comment by iyilm4z** [comment]
@vivekpatel19 thank you for your feedback. I will take care of this.

**Comment by iyilm4z** [comment]
@vivekpatel19 I took a look at the repo and I found it so simple. That’s why I couldn’t find how to document it. If you want to contribute it, you are welcome. Fell free to reopen the issue.
